{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-vision.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-vision.labels" . | nindent 4 }}
{{- end }}
